### ISSUE TITLE
sample.env

### ISSUE THREAD

**Issue by adhamhagras76** [Soneium/soneium-node#12]
I am new to this so i hope my question is not so stupid, when i paste the command mv sample.env .env i get this error message mv: cannot stat 'sample.env': No such file or directory,, how can i fix this?

**Comment by ehsanhajian** [comment]
after cloning the repo run `cd soneium-node/minato` then run the `mv` command.

**Comment by adhamhagras76** [comment]
worked, thanks
but the next code come up with this error:
PS C:\Users\adham\soneium-node\minato> docker-compose logs -f op-node-minato
op-node-minato-1  | t=2024-10-15T20:55:56+0000 lvl=warn msg="Unknown env var" prefix=OP_NODE env_var="OP_NODE_STATIC_PEERS=/dns4/peering-01.prd.hypersonicl2.com/tcp/9222/p2p/16Uiu2HAm36ufaFmS3tjSjkUnwSJmQN8W8fZ8yXiu2AYL2o11EgcK,/dns4/peering-02.prd.hypersonicl2.com/tcp/9222/p2p/16Uiu2HAmPkRbG8kkhJ3JWmrqeiMvy1hWXFSz4s4rncVe8YiCJHmx"
op-node-minato-1  | t=2024-10-15T20:55:56+0000 lvl=crit msg="Application failed" message="failed to setup: unable to create the rollup node config: failed to read rollup config: open : no such file or directory"

**Comment by ehsanhajian** [comment]
Please read the doc carefully and set all required `envs`. I'm closing this issue.
