### ISSUE TITLE
Unable to Claim Sepolia After Multiple Attempts

### ISSUE THREAD

**Issue by Crack000-Com** [Soneium/soneium-node#14]
Hi,

I have encountered a persistent issue with claiming Sepolia. Yesterday, I attempted to add more Sepolia to my balance and tried claiming it again, but I was still unable to complete the transaction. Today, I added even more Sepolia and retried the claim process, but unfortunately, the transaction still fails.

As seen in the attached screenshots, I have sufficient Sepolia ETH in my balance, yet the claim process remains unsuccessful. Could you please help me resolve this?

Looking forward to your guidance.

![IMG_20241016_144743](https://github.com/user-attachments/assets/80cd66ef-7daa-49d2-85e3-1862acdcd56e)
![IMG_20241016_144728](https://github.com/user-attachments/assets/a08bcfff-d4dc-4483-8516-2fc70c8c7d58)
![IMG_20241016_053730](https://github.com/user-attachments/assets/57574a4e-f1fc-4db5-b966-0411513a4b12)

**Comment by Gunit2481** [comment]
@Crack000-Com Can you share a screenshot of your development console error report when you get the notification of failure? 

`Right-click` on the page > `Inspect`, then in the window that appears on the right, select the `console` and check the error.

https://balsamiq.com/support/faqs/browserconsole/#google-chrome

If you need further assistance, please join[ Soneium's Discord](https://discord.com/invite/soneium) and open a ticket. It will be easier for support team to help you.

**Comment by Crack000-Com** [comment]
I don't have a computer, I'm only using my phone, so I can't access the developer console as you mentioned. Is there an alternative way to check errors or send logs directly from a mobile browser? I would really appreciate any help, as I can't use desktop tools.
