### ISSUE TITLE
Persian-Elite 

### ISSUE THREAD

**Issue by Morteza-Abolhassani-Khajeh** [Soneium/soneium-node#16]
I have never been so sad and upset, when you are helping users who are confused and don't even know where they are and what they are talking about, you are helping them, giving them your experiences, your information, and guiding them, all of a sudden.  You notice that Discord has blocked you and restricted your access, you ask why and for what reason, they say, well, you are Iranian and Iran is sanctioned by the international community, you say Iran is sanctioned, elite and intelligent Iranians are also sanctioned...  ..!!!!??????

**Comment by Morteza-Abolhassani-Khajeh** [comment]
#soneium
#international
#iran
#embargo

**Comment by ehsanhajian** [comment]
Hi Morteza, I'm closing this issue as no questions or issues have been asked. Please consider asking your questions in the GitHub issue, and we try to help.
