### ISSUE TITLE
soneium-node running error

### ISSUE THREAD

**Issue by aweio9** [Soneium/soneium-node#18]
lvl=crit msg="Application failed" message="failed to setup: unable to create the rollup node: failed to init L1: failed to get L1 RPC client: failed to dial L1 address (https://sepolia-l1.url): operation failed permanently after 10 attempts: address unavailable (https://sepolia-l1.url)"
minato_op-node-minato_1 exited with code 1

**Comment by ehsanhajian** [comment]
This is not an issue. You need to set l1 address in your config. maybe this can help you.
https://github.com/Soneium/soneium-node/issues/13#issuecomment-2417074708
