### ISSUE TITLE
unable to curl op-node if use 127.0.0.1 but 0.0.0.0 works fine

### ISSUE THREAD

**Issue by Obiwank107** [Soneium/soneium-node#22]
.env
Unable to curl op-node when use RPC_ADDR=127.0.0.1
Able to curl op-node if use RPC_ADDR=0.0.0.0

command 
curl -X POST -H "Content-Type: application/json" --data \
    '{"jsonrpc":"2.0","method":"optimism_syncStatus","params":[],"id":1}' \
    http://localhost:9545 | jq

**Comment by tksarah** [comment]
Yes, I think that's correct.
You are probably setting up the node with containers in mind, 
but by default, the .env used for container startup has the op-node RPC listening on the loopback address.

**Comment by ehsanhajian** [comment]
https://github.com/Soneium/soneium-node/pull/23#issuecomment-2456295531

**Comment by ehsanhajian** [comment]
I'm closing this issue as no more comments was received.
