### ISSUE TITLE
when restart node op-geth got an error Fatal: Failed to write genesis block: mismatching Fjord fork timestamp in database

### ISSUE THREAD

**Issue by Obiwank107** [Soneium/soneium-node#24]
when I restart node always got an error  "Fatal: Failed to write genesis block: mismatching Fjord fork timestamp in database (have timestamp 1730106000, want timestamp nil, rewindto timestamp 1730105999)"
I've tried 3 times with different server and reinstall node and start syncing from scratch when restart node it happened every time.
Before restart my node works fine.

<img width="1376" alt="Screenshot 2567-11-06 at 02 19 13" src="https://github.com/user-attachments/assets/3e0b7fcc-167a-4f63-a275-30eb32a15ab8">

**Comment by ehsanhajian** [comment]
Hi, if you sync a node from scratch, please make sure to delete the `op-geth` and `op-node` docker volumes.

```
docker volume rm minato_op-geth-storage
docker volume rm minato_op-node-storage
docker volume rm minato_op-secrets
```

**Comment by Obiwank107** [comment]
> Hi, if you sync a node from scratch, please make sure to delete the `op-geth` and `op-node` docker volumes.
> 
> ```
> docker volume rm minato_op-geth-storage
> docker volume rm minato_op-node-storage
> docker volume rm minato_op-secrets
> ```

Yes, I've delete before start node. When sync is completed I did restart node and got error.
Now I will try again not syncing will have a few day to 100% synced. I'll update again.
Regards.

**Comment by Obiwank107** [comment]
@ehsanhajian  I want to update  my issue.
Firstly, I ran minato and start sync from scratch, I deleted the op-geth and op-node docker volumes. before node start.
It takes a little long time for finding peer, but syncing smoothly. my geth log below.
![image](https://github.com/user-attachments/assets/a7ee09f9-7ee3-4b6b-a215-8093944f9895)

In the catching up process, I've restarted geth 1 time and resume syncing smoothly.
then,
I use 1 day for catching up to the latest block, finally my Minato node is 100% synced. geth log below.
<img width="1424" alt="Screenshot 2567-11-07 at 19 18 56" src="https://github.com/user-attachments/assets/0b86eae8-d679-433a-bf42-b852dfe99891">

And then, I test restarting geth after my node 100% synced but I got an error "Fatal: Failed to write genesis block: mismatching Fjord fork timestamp in database (have timestamp 1730106000, want timestamp nil, rewindto timestamp 1730105999)" same as before, I don't know why but my node can't startup anymore. geth error logs below
<img width="1413" alt="Screenshot 2567-11-07 at 19 27 40" src="https://github.com/user-attachments/assets/8bc13ee6-62fc-40a1-a230-236c205ae602">

Regards.

**Comment by MehrnoshHdi** [comment]
Hello soneium

**Comment by MehrnoshHdi** [comment]
Good days family soneium

**Comment by Obiwank107** [comment]
> Yes, confirmed. There is an issue with the `geth` initialization script. As a workaround, you can remove the following lines from the Docker Compose file, and your synced node should work properly
> 
> ```
>       cp /config/minato-genesis.json /data/optimism/genesis.json &&
>       geth init --state.scheme=hash --datadir=/data/optimism /data/optimism/genesis.json &&
> ```
> 
> I'll fix the script.

<img width="1422" alt="Screenshot 2567-11-08 at 15 20 34" src="https://github.com/user-attachments/assets/851379bc-7269-4a33-a040-e84aca6e90d9">
Thanks, It works.
