### ISSUE TITLE
Cannot clone the Sonrium Node

### ISSUE THREAD

**Issue by cryptobike07** [Soneium/soneium-node#9]
Cloning into 'soneium-node'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ehsanhajian** [comment]
https://github.com/Soneium/soneium-node/pull/11
resolved. thanks

**Comment by cryptobike07** [comment]
I succesfully running now. Thanks alot!
